"use server";

import { GoogleGenAI, Type } from "@google/genai";
import { localAnalyzeRisk, localGenerateRecoveryPlan } from "@/lib/localAi";
import { Task } from "@/types";

export async function geminiDeepSuggestion(tasks: Task[], userApiKey?: string): Promise<{
  success: boolean;
  data?: { headline: string; suggestion: string; focusTip: string; productivityScore: number };
  error?: string;
}> {
  const apiKey = userApiKey || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return { success: false, error: "GEMINI_API_KEY not set." };
  }
  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `You are a personal productivity coach AI. Analyze the following task list and generate a deep planning suggestion.
      
Tasks: ${JSON.stringify(tasks, null, 2)}

Generate a personalized insight with:
- A short punchy headline (max 6 words)
- A 2-3 sentence planning suggestion that references the actual tasks
- A single actionable focus tip for today
- A productivity score out of 100 based on completion rate and deadline health`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            headline: { type: Type.STRING },
            suggestion: { type: Type.STRING },
            focusTip: { type: Type.STRING },
            productivityScore: { type: Type.NUMBER }
          },
          required: ["headline", "suggestion", "focusTip", "productivityScore"]
        }
      }
    });
    if (response.text) {
      return { success: true, data: JSON.parse(response.text) };
    }
    return { success: false, error: "No response from Gemini." };
  } catch (err: unknown) {
    return { success: false, error: err instanceof Error ? err.message : "Gemini request failed." };
  }
}

export async function generateTaskFromText(inputText: string, userApiKey?: string) {
  const apiKey = userApiKey || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return { success: false, error: "GEMINI_API_KEY is not set in environment variables." };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Convert the following user input into a structured task. If no deadline is specified, set it to 3 days from now.
      
      User Input: "${inputText}"`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING, description: "A concise title for the task (max 5 words)" },
            description: { type: Type.STRING, description: "A detailed description of the task based on the input" },
            deadline: { type: Type.STRING, description: "ISO date string of the deadline" },
            priority: { type: Type.STRING, enum: ["Low", "Medium", "High"], description: "Inferred priority of the task" },
            category: { type: Type.STRING, description: "Inferred category (e.g., Engineering, Study, Personal)" },
            estimatedHours: { type: Type.NUMBER, description: "Estimated time in hours to complete this task" }
          },
          required: ["title", "description", "deadline", "priority", "category", "estimatedHours"]
        }
      }
    });

    if (response.text) {
      return { success: true, data: JSON.parse(response.text) };
    } else {
      return { success: false, error: "No response text generated by AI." };
    }
  } catch (error: unknown) {
    console.error("AI Generation Error:", error);
    return { success: false, error: error instanceof Error ? error.message : "Failed to generate task using AI." };
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateSchedule(tasks: Task[], userProfile?: Record<string, any>, userApiKey?: string) {
  const apiKey = userApiKey || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return { success: false, error: "GEMINI_API_KEY is not set." };
  }

  if (tasks.length === 0) {
    return { success: false, error: "No tasks provided to generate a schedule." };
  }
  
  let userContextStr = "";
  if (userProfile) {
    userContextStr = `\n\nUSER CONTEXT:\nThe user is a ${userProfile.profession} working from ${userProfile.workingHoursStart} to ${userProfile.workingHoursEnd}.
    They have provided the following custom instructions for scheduling: "${userProfile.customInstructions}".
    Strictly adhere to these constraints and do not generate random schedules outside these parameters. Only schedule tasks within their working hours.`;
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Create an optimized 3-day schedule for the following tasks. Place high priority tasks during morning focus blocks (or early in their working hours). 
      Tasks: ${JSON.stringify(tasks, null, 2)}${userContextStr}`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            reasoning: { type: Type.STRING, description: "Explanation of why this schedule was chosen" },
            workload: { type: Type.NUMBER, description: "Estimated workload percentage (0-100)" },
            strategicFocus: { type: Type.NUMBER, description: "Total focus hours scheduled" },
            efficiency: { type: Type.NUMBER, description: "Efficiency score percentage" },
            burnoutRisk: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
            days: {
              type: Type.ARRAY,
              description: "Array of 3 days",
              items: {
                type: Type.OBJECT,
                properties: {
                  dayName: { type: Type.STRING, description: "E.g. Monday" },
                  date: { type: Type.NUMBER, description: "Day of the month" },
                  slots: {
                    type: Type.ARRAY,
                    items: {
                      type: Type.OBJECT,
                      properties: {
                        taskTitle: { type: Type.STRING },
                        timeRange: { type: Type.STRING, description: "E.g. 09:00 AM - 11:00 AM" },
                        type: { type: Type.STRING, enum: ["Focus Block", "Routine", "Skill Dev", "Meeting"] }
                      },
                      required: ["taskTitle", "timeRange", "type"]
                    }
                  }
                },
                required: ["dayName", "date", "slots"]
              }
            }
          },
          required: ["reasoning", "workload", "strategicFocus", "efficiency", "burnoutRisk", "days"]
        }
      }
    });

    if (response.text) {
      return { success: true, data: JSON.parse(response.text) };
    } else {
      return { success: false, error: "No response text generated by AI." };
    }
  } catch (error: unknown) {
    console.error("AI Schedule Generation Error:", error);
    return { success: false, error: error instanceof Error ? error.message : "Failed to generate schedule using AI." };
  }
}

export async function analyzeRisk(tasks: Task[], userApiKey?: string) {
  const apiKey = userApiKey || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return { success: true, data: localAnalyzeRisk(tasks), isFallback: true };
  }

  if (tasks.length === 0) {
    return { success: false, error: "No tasks provided for risk analysis." };
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Analyze the following tasks for deadline risk based on their deadlines, priorities, and current status. Return an overall risk assessment. 
      Tasks: ${JSON.stringify(tasks, null, 2)}`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            riskLevel: { type: Type.STRING, enum: ["Low", "Medium", "High"] },
            reasoning: { type: Type.STRING, description: "Why this risk level was assigned" },
            urgentTasks: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "Titles of tasks that are at risk"
            }
          },
          required: ["riskLevel", "reasoning", "urgentTasks"]
        }
      }
    });

    if (response.text) {
      return { success: true, data: JSON.parse(response.text), isFallback: false };
    } else {
      return { success: false, error: "No response text generated by AI." };
    }
  } catch (error: unknown) {
    console.warn("⚠️ AI Risk Analysis failed. Using local fallback...", error);
    return { success: true, data: localAnalyzeRisk(tasks), isFallback: true };
  }
}

export async function generateRecoveryPlan(delayedTasks: Task[], userApiKey?: string) {
  const apiKey = userApiKey || process.env.GEMINI_API_KEY;
  try {
    if (!apiKey) throw new Error("No API key");

    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Generate a recovery plan for the following delayed/overdue tasks to get back on track.
      Tasks: ${JSON.stringify(delayedTasks, null, 2)}`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            strategy: { type: Type.STRING, description: "Overall recovery strategy" },
            actionSteps: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "Specific actionable steps to take immediately"
            }
          },
          required: ["strategy", "actionSteps"]
        }
      }
    });

    if (response.text) {
      return { success: true, data: JSON.parse(response.text), isFallback: false };
    } else {
      return { success: false, error: "No response text generated by AI." };
    }
  } catch (error: unknown) {
    console.warn("⚠️ AI Recovery Plan failed. Using local fallback...", error);
    return { success: true, data: localGenerateRecoveryPlan(delayedTasks), isFallback: true };
  }
}

const insightsCache = new Map<string, { riskAnalysis: unknown; recoveryPlan: unknown }>();

export async function getInsights(taskHash: string, tasksData: Task[], delayedTasks: Task[], userApiKey?: string) {
  const cacheKey = `${taskHash}_${userApiKey || 'default'}`;
  if (insightsCache.has(cacheKey)) {
    console.log("🎯 Serving insights from Server In-Memory Cache!");
    return { success: true, data: insightsCache.get(cacheKey), isFallback: false };
  }
  
  try {
    console.log("🤖 Server Cache Miss. Calling Gemini API...");
    
    const riskRes = await analyzeRisk(tasksData, userApiKey);
    if (!riskRes.success) {
      return { success: false, error: riskRes.error };
    }
    
    let recoveryRes = null;
    let recoveryFallback = false;
    if (delayedTasks.length > 0) {
      const recRes = await generateRecoveryPlan(delayedTasks, userApiKey);
      if (!recRes.success) {
        return { success: false, error: recRes.error };
      }
      recoveryRes = recRes.data;
      recoveryFallback = !!recRes.isFallback;
    }
    
    const result = {
      riskAnalysis: riskRes.data,
      recoveryPlan: recoveryRes
    };
    
    insightsCache.set(cacheKey, result);
    return { success: true, data: result, isFallback: !!riskRes.isFallback || recoveryFallback };
  } catch (error: unknown) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const err = error as any;
    const isRateLimit = err?.message?.includes("429") || err?.status === 429;
    return {
      success: false,
      error: isRateLimit
        ? "Gemini API rate limit or daily quota exceeded. Please try again in a few minutes."
        : (err?.message || "An unexpected error occurred.")
    };
  }
}
